version: '3.8'
services:
  web-oauth-app:
    container_name: web-oauth-app
    image: web-oauth-app
    hostname: web-oauth-app
    build:
      context: ./
      target: production
    environment:
      GOOGLE_CLIENT_ID: 86598659yu
      GOOGLE_CLIENT_SECRET: 86598659yu
    restart: always
    ports:
      - 3000:3000
    networks:
      - web-oauth-network
      
  web-oauth-mongodb:
    image: mongo
    restart: always
    container_name: web-oauth-mongodb
    hostname: web-oauth-mongodb
    environment:
      MONGO_INITDB_DATABASE: webOAuthProject
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - 27017:27017
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - web-oauth-mongodb-data:/data/db
    networks:
      - web-oauth-network

volumes:
  web-oauth-mongodb-data:
# Set network as web-oauth-network
networks:
  web-oauth-network: