version: '3.9'
services:
  web-oauth-app:
    container_name: web-oauth-app
    image: web-oauth-app:latest
    hostname: web-oauth-app
    build:
      context: ./
      target: production
    env_file:
      - ./.env.local
    environment:
    #   GOOGLE_CLIENT_ID: <REPLACE_YOUR_GOOGLE_CLIENT_ID>
    #   GOOGLE_CLIENT_SECRET: <REPLACE_YOUR_GOOGLE_CLIENT_ID>
    #   REGRES_API_BASE_URL: https://reqres.in/api
    #   NEXTAUTH_SECRET: secret
    #   NEXTAUTH_DEBUG: false
    #   JWT_SECRET_KEY: secret
      MONGODB_URI: mongodb://admin:adminpassword@web-oauth-mongodb:27017/web-oauth
    ports:
      - 3000:3000
    depends_on:
      - web-oauth-mongodb
    networks:
      - web-oauth-network
      
  web-oauth-mongodb:
    image: mongo
    restart: always
    container_name: web-oauth-mongodb
    hostname: web-oauth-mongodb
    environment:
      MONGO_INITDB_DATABASE: web-oauth
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - 27017:27017
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - web-oauth-mongodb-data:/data/db
    networks:
      - web-oauth-network

# Set volumes for db as a named volume
volumes:
  web-oauth-mongodb-data:
    driver: local # Use local driver for named volume
# Set network as web-oauth-network
networks:
  web-oauth-network:
    driver: bridge # default driver is bridge only, we don't need to specify it explicitly